name: Generate DZMM EPG (Weekly)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 */7 * *'  # every 7 days at 3:00 AM Manila (UTC+8)
  push:
    branches: [main]
    paths-ignore:
      - 'dzmm.xml'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate DZMM XMLTV
        run: python dzmm_epg.py

      - name: Commit and push updated EPG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dzmm.xml
          if git diff --cached --quiet; then
            echo "No changes detected — skipping commit."
          else
            git commit -m "🗓️ Weekly DZMM EPG update [skip ci]"
            git push
          fi
